// <auto-generated />
using System;
using BookingAPI.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingAPI.Services.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20181125180040_ReservationMigration")]
    partial class ReservationMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookingAPI.Services.Entity.Reservation", b =>
                {
                    b.Property<string>("GuRecId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Qty");

                    b.Property<DateTimeOffset>("ReservationDate");

                    b.HasKey("GuRecId");

                    b.ToTable("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
